# Site settings
title: COLORTAB
description: "COLORTAB is a collation of colors available on Github that can be used within your CSS using SASS variables to make referencing the colors easier."
baseurl: ""
url: "http://colortab.co.uk"

# Build settings
markdown: kramdown
exclude: [node_modules]
